Onboard to shared CI
Signed-off-by: Adam Cmiel <acmiel@redhat.com>

diff --git a/.github/workflows/check-task-migration.yaml b/.github/workflows/check-task-migration.yaml
--- a/.github/workflows/check-task-migration.yaml
+++ b/.github/workflows/check-task-migration.yaml
@@ -1,3 +1,10 @@
+# yamllint disable-file
+
+# <TEMPLATED FILE!>
+# This file comes from the templates at https://github.com/konflux-ci/task-repo-shared-ci.
+# Please consider sending a PR upstream instead of editing the file directly.
+# See the SHARED-CI.md document in this repo for more details.
+
 name: Check task migrations
 "on":
   pull_request:
@@ -9,16 +16,26 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
         with:
           fetch-depth: 0
       - name: Create k8s Kind Cluster
-        uses: helm/kind-action@v1.12.0
+        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
         with:
           cluster_name: kind
       - uses: tektoncd/actions/setup-tektoncd@main
+        id: setup-tektoncd
         with:
           pipeline_version: latest
+        continue-on-error: true
+      - name: Describe setup-tektoncd failure
+        if: steps.setup-tektoncd.outcome != 'success'
+        run: |
+          curl -s https://api.github.com/repos/tektoncd/pipeline/releases/latest | jq
+          echo "The previous action setup-tektoncd seems to have failed due to a known issue caused by hitting the rate-limit"
+          echo "For more information, follow the following issue: https://github.com/tektoncd/actions/issues/9"
+          echo "The only known workaround at the moment is to re-run this workflow."
+          exit 1
       - name: Run check
         run: |
           DEBIAN_FRONTEND=noninteractive \
